name: RDP with LocalXpose

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download LocalXpose Portable
        run: |
          Invoke-WebRequest https://localxpose.io/releases/lx-windows-amd64.zip -OutFile lx.zip
          Expand-Archive lx.zip -DestinationPath .
          echo "LocalXpose downloaded"

      - name: Enable RDP + Start Tunnel
        run: |
          net user kamel123 MyStrong123 /add
          net localgroup administrators kamel123 /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          .\lx.exe auth 4szdbKgf1A38QVPw2KDtvJeiEQvojc8gs1f5FI9c
          .\lx.exe tunnel tcp --port 3389 --log stdout
